version: "2"
services:
  node:
    image: "node:15.7.0"
    user: "node"
    working_dir: /home/node/app
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/app
    command: "npx nodemon index.js"