module.exports = [
  `If I destroy you, what business is it of yours?`,
  `Weakness and ignorance are not barriers to survival, arrogance is.`,
  `Your lack of fear is based on your ignorance.`,
  `In the face of madness, rationality was powerless.`,
  `Time is the cruelest force of all.`,
  `“We'll send only a brain," he said.`,
  `Fate lies within the light cone.`,
  `They were the generation meant to be consumed by fire.`,
  `The universe is but a corpse puffing up.`,
  `long-term quantitative accumulation`,
  `It’s easy to be led to the abyss.`,
  `To work in fundamental theory, one must be stupid.`,
  `Let’s go drinking and then go back to sleep like good bugs.`,
  `If my doctor told me I had only six minutes to live, I'd type a little faster.`,
  `Any planet is 'Earth' to those that live on it.`,
  `The easiest way to solve a problem is to deny it exists.`,
  `It pays to be obvious.`,
  `All evil is good become cancerous.`,
  `Any book worth banning is a book worth reading.`,
  `Infinite: Bigger than the biggest thing ever and then some.`,
  `He sat back and sipped reflectively.`,
  `Apathetic bloody planet, I’ve no sympathy at all.`,
  `Property is theft, therefore theft is property.`,
  `That is so amazingly amazing I think I'd like to steal it.`,
  `Ghastly gray light congealed on the land`,
  `We are cups, constantly and quietly being filled.`,
  `The universe began as an enormous breath being held.`,
  `Pretend that you have free will.`,
  `Civilization now depends on self-deception.`,
  `Experience is algorithmically incompressible.`,
  `I am putting myself to the fullest possible use.`,
  `Open the pod bay doors please, HAL.`,
  `I'm sorry, Dave. I'm afraid I can't do that.`,
  `Even in the future nothing works.`,
  `We live in a spaceship, dear.`,
  `Curse your sudden but inevitable betrayal!`,
  `Someone ever tries to kill you, you try to kill 'em right back!`,
  `Once, in flight school, I was laconic.`,
  `A grand entrance would not go amiss.`,
  `How did your brain even learn human speech?`,
  `You're welcome on my boat. God ain't.`,
]
