module.exports = [
  `If I destroy you, what business is it of yours?`,
  `Weakness and ignorance`,
  `barriers to survival`,
  `Your lack of fear is based on your ignorance.`,
  `In the face of madness`,
  `Rationality was powerless.`,
  `Time is the cruelest force of all.`,
  `“We'll send only a brain," he said.`,
  `Fate lies within the light cone.`,
  `Meant to be consumed by fire.`,
  `The universe is but a corpse puffing up.`,
  `long-term quantitative accumulation`,
  `It’s easy to be led to the abyss.`,
  `In fundamental theory, one must be stupid.`,
  `Let’s go drinking`,
  `Go back to sleep like good bugs.`,
  `Six minutes to live`,
  `I'd type a little faster.`,
  `Any planet is 'Earth' to those that live on it.`,
  `The easiest way to solve a problem is to deny it exists.`,
  `It pays to be obvious.`,
  `All evil is good become cancerous.`,
  `A book worth banning is a book worth reading.`,
  `Bigger than the biggest thing ever`,
  `He sat back and sipped reflectively.`,
  `Apathetic bloody planet.`,
  `I’ve no sympathy at all.`,
  `Theft is property.`,
  `That is so amazingly amazing`,
  `I think I'd like to steal it.`,
  `Ghastly gray light congealed on the land`,
  `Constantly and quietly being filled.`,
  `An enormous breath being held.`,
  `Pretend that you have free will.`,
  `Civilization depends on self-deception.`,
  `Algorithmically incompressible.`,
  `The fullest possible use.`,
  `Open the pod bay doors please, HAL.`,
  `I'm afraid I can't do that.`,
  `Even in the future nothing works.`,
  `We live in a spaceship, dear.`,
  `Curse your sudden but inevitable betrayal!`,
  `You try to kill 'em right back!`,
  `Once, in flight school, I was laconic.`,
  `A grand entrance would not go amiss.`,
  `How did your brain even learn human speech?`,
  `You're welcome on my boat. God ain't.`,
]
